# Generated by Django 3.2 on 2022-08-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banner_dj', '0003_auto_20220806_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannerstyle',
            name='float',
        ),
    ]
