# Generated by Django 3.2 on 2022-08-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banner_dj', '0004_remove_bannerstyle_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerstyle',
            name='image_fit',
            field=models.CharField(choices=[('unset', 'Unset'), ('cover', 'Cover'), ('contain', 'Contain')], default='unset', max_length=10),
        ),
    ]
