# Generated by Django 3.2 on 2022-08-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banner_dj', '0005_bannerstyle_image_fit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerstyle',
            name='height_smallsize',
            field=models.CharField(default='auto', help_text='You can set "auto" or percentage like "50%" or pixle like "200px" value', max_length=10),
        ),
        migrations.AddField(
            model_name='bannerstyle',
            name='width_smallsize',
            field=models.CharField(default='auto', help_text='You can set "auto" or percentage like "50%" or pixle like "200px" value', max_length=10),
        ),
    ]
